CREATE TEMPORARY TABLESPACE note_TEMP
         TEMPFILE 'f:note_TEMP.DBF'
         SIZE 128M
         AUTOEXTEND ON
         NEXT 128M MAxSIZE UNLIMITED
         EXTENT MANAGEMENT LOCAL;
CREATE TABLESPACE note_DATA
         LOGGING
         DATAFILE 'f:note_DATA.DBF'
         SIZE 128M
         AUTOEXTEND ON
         NEXT 128M MAXSIZE UNLIMITED
         EXTENT MANAGEMENT LOCAL;
         
CREATE USER note IDENTIFIED BY note
         ACCOUNT UNLOCK
         DEFAULT TABLESPACE note_DATA
         TEMPORARY TABLESPACE note_TEMP;
         
GRANT CONNECT,RESOURCE TO note; 
GRANT DBA TO note;
